
var indTestData=
	[
	  {
	    "id": "54548fddeaec8bd80f33972d",
	    "fbid": 0,
	    "opendata": 0,
	    "industry": 22,
	    "industrystring" : "教育服務",
	    "jobcat": 3,
	    "jobcatstring" : "人力資源",
	    "club_id": 1,
	    "name": "張三",
	    "company": "TRI@TRIBALOG",
	    "phone": "+1 (807) 504-3334",
	    "jobtitle": "Engineer",
	    "otherData": "Hello, function (){return e.surname=c.getItem(\"surnames\"),e.surname}"
	  },
	  {
	    "id": "54548fdde1f8bbea2ed6146f",
	    "fbid": 1,
	    "opendata": 1,
	    "industry": 22,
	    "industrystring" : "教育服務",
	    "jobcat": 33,
	    "jobcatstring" : "行政後勤",
	    "club_id": 2,
	    "name": "李四",
	    "company": "ASSISTIX",
	    "phone": "+1 (829) 463-3878",
	    "jobtitle": "Engineer",
	    "otherData": "Hello, function (){return e.surname=c.getItem(\"surnames\"),e.surname}"
	  },
	  {
	    "id": "54548fddf4fddb3d61522fe5",
	    "fbid": 2,
	    "opendata": 1,
	    "industry": 22,
	    "industrystring" : "教育服務",
	    "jobcat": 27,
	    "jobcatstring" : "法務專利",
	    "club_id": 2,
	    "name": "王五",
	    "company": "SAVVY",
	    "phone": "+1 (938) 546-2557",
	    "jobtitle": "GoodMan",
	    "otherData": "Hello, function (){return e.surname=c.getItem(\"surnames\"),e.surname}"
	  },
	  {
	    "id": "54548fdd26b89e15e045a481",
	    "fbid": 3,
	    "opendata": 1,
	    "industry": 22,
	    "industrystring" : "教育服務",
	    "jobcat": 30,
	    "jobcatstring" : "生活服務",
	    "club_id": 3,
	    "name": "劉陸",
	    "company": "SNORUS",
	    "phone": "+1 (921) 522-3227",
	    "jobtitle": "Engineer",
	    "otherData": "Hello, function (){return e.surname=c.getItem(\"surnames\"),e.surname}"
	  },
	  {
	    "id": "54548fdd6bbf9728f24daa60",
	    "fbid": 4,
	    "opendata": 0,
	    "industry": 22,
	    "industrystring" : "教育服務",
	    "jobcat": 38,
	    "jobcatstring" : "補習進修",
	    "club_id": 4,
	    "name": "董八",
	    "company": "BIOLIVE",
	    "phone": "+1 (843) 437-2745",
	    "jobtitle": "Teacher",
	    "otherData": "Hello, function (){return e.surname=c.getItem(\"surnames\"),e.surname}"
	  },
	  {
	    "id": "54548fdddaa96432ec122cff",
	    "fbid": 5,
	    "opendata": 0,
	    "industry": 22,
	    "industrystring" : "教育服務",
	    "jobcat": 28,
	    "jobcatstring" : "幼兒教育",
	    "club_id": 11,
	    "name": "力艾",
	    "company": "AFFLUEX",
	    "phone": "+1 (869) 484-2059",
	    "jobtitle": "Engineer",
	    "otherData": "Hello, function (){return e.surname=c.getItem(\"surnames\"),e.surname}"
	  },
	  {
		    "id": "54548fddeaec8bd80f33972d",
		    "fbid": 0,
		    "opendata": 0,
		    "industry": 22,
		    "industrystring" : "教育服務",
		    "jobcat": 3,
		    "jobcatstring" : "人力資源",
		    "club_id": 1,
		    "name": "張三",
		    "company": "TRI@TRIBALOG",
		    "phone": "+1 (807) 504-3334",
		    "jobtitle": "Engineer",
		    "otherData": "Hello, function (){return e.surname=c.getItem(\"surnames\"),e.surname}"
		  },
		  {
		    "id": "54548fdde1f8bbea2ed6146f",
		    "fbid": 1,
		    "opendata": 1,
		    "industry": 22,
		    "industrystring" : "教育服務",
		    "jobcat": 33,
		    "jobcatstring" : "行政後勤",
		    "club_id": 2,
		    "name": "李四",
		    "company": "ASSISTIX",
		    "phone": "+1 (829) 463-3878",
		    "jobtitle": "Engineer",
		    "otherData": "Hello, function (){return e.surname=c.getItem(\"surnames\"),e.surname}"
		  },
		  {
		    "id": "54548fddf4fddb3d61522fe5",
		    "fbid": 2,
		    "opendata": 1,
		    "industry": 22,
		    "industrystring" : "教育服務",
		    "jobcat": 27,
		    "jobcatstring" : "法務專利",
		    "club_id": 2,
		    "name": "王五",
		    "company": "SAVVY",
		    "phone": "+1 (938) 546-2557",
		    "jobtitle": "GoodMan",
		    "otherData": "Hello, function (){return e.surname=c.getItem(\"surnames\"),e.surname}"
		  },
		  {
		    "id": "54548fdd26b89e15e045a481",
		    "fbid": 3,
		    "opendata": 1,
		    "industry": 22,
		    "industrystring" : "教育服務",
		    "jobcat": 30,
		    "jobcatstring" : "生活服務",
		    "club_id": 3,
		    "name": "劉陸",
		    "company": "SNORUS",
		    "phone": "+1 (921) 522-3227",
		    "jobtitle": "Engineer",
		    "otherData": "Hello, function (){return e.surname=c.getItem(\"surnames\"),e.surname}"
		  },
		  {
		    "id": "54548fdd6bbf9728f24daa60",
		    "fbid": 4,
		    "opendata": 0,
		    "industry": 22,
		    "industrystring" : "教育服務",
		    "jobcat": 38,
		    "jobcatstring" : "補習進修",
		    "club_id": 4,
		    "name": "董八",
		    "company": "BIOLIVE",
		    "phone": "+1 (843) 437-2745",
		    "jobtitle": "Teacher",
		    "otherData": "Hello, function (){return e.surname=c.getItem(\"surnames\"),e.surname}"
		  },
		  {
		    "id": "54548fdddaa96432ec122cff",
		    "fbid": 5,
		    "opendata": 0,
		    "industry": 22,
		    "industrystring" : "教育服務",
		    "jobcat": 28,
		    "jobcatstring" : "幼兒教育",
		    "club_id": 11,
		    "name": "力艾",
		    "company": "AFFLUEX",
		    "phone": "+1 (869) 484-2059",
		    "jobtitle": "Engineer",
		    "otherData": "Hello, function (){return e.surname=c.getItem(\"surnames\"),e.surname}"
		  }
	];

var jobTestData=
	[
	  {
	    "id": "5454904a791dbc7678b10b1a",
	    "fbid": 0,
	    "opendata": 1,
	    "industry": 26,
	    "industrystring" : "教育服務",
	    "jobcat": 11,
	    "jobcatstring" :"醫事人員",
	    "club_id": 1,
	    "name": "張三",
	    "company": "ELPRO",
	    "phone": "+1 (802) 528-3714",
	    "jobtitle": "GoodMan",
	    "otherData": "Hello, function (){return e.surname=c.getItem(\"surnames\"),e.surname}"
	  },
	  {
	    "id": "5454904ae7488f97b3feebb8",
	    "fbid": 1,
	    "opendata": 0,
	    "industry": 25,
	    "industrystring" : "環境衛生",
	    "jobcat": 11,
	    "jobcatstring" :"醫事人員",
	    "club_id": 2,
	    "name": "李四",
	    "company": "INSURITY",
	    "phone": "+1 (829) 504-3922",
	    "jobtitle": "Teacher",
	    "otherData": "Hello, function (){return e.surname=c.getItem(\"surnames\"),e.surname}"
	  },
	  {
	    "id": "5454904a6ffaf0d2baf29bec",
	    "fbid": 2,
	    "opendata": 0,
	    "industry": 11,
	    "industrystring" : "批發零售",
	    "jobcat": 11,
	    "jobcatstring" :"醫事人員",
	    "club_id": 3,
	    "name": "James",
	    "company": "PASTURIA",
	    "phone": "+1 (958) 403-2590",
	    "jobtitle": "Teacher",
	    "otherData": "Hello, function (){return e.surname=c.getItem(\"surnames\"),e.surname}"
	  },
	  {
	    "id": "5454904ab2b089d8c69b7eae",
	    "fbid": 3,
	    "opendata": 0,
	    "industry": 5,
	    "industrystring" : "人力仲介",
	    "jobcat": 11,
	    "jobcatstring" :"醫事人員",
	    "club_id": 3,
	    "name": "Kevin",
	    "company": "MATRIXITY",
	    "phone": "+1 (929) 460-3039",
	    "jobtitle": "Teacher",
	    "otherData": "Hello, function (){return e.surname=c.getItem(\"surnames\"),e.surname}"
	  },
	  {
	    "id": "5454904ac72a8687c53d008d",
	    "fbid": 4,
	    "opendata": 1,
	    "industry": 12,
	    "industrystring" : "光電光學",
	    "jobcat": 11,
	    "jobcatstring" :"醫事人員",
	    "club_id": 3,
	    "name": "Amy",
	    "company": "NORALI",
	    "phone": "+1 (894) 549-2678",
	    "jobtitle": "Engineer",
	    "otherData": "Hello, function (){return e.surname=c.getItem(\"surnames\"),e.surname}"
	  },
	  {
	    "id": "5454904a9c48c7c3ef00dc0b",
	    "fbid": 5,
	    "opendata": 0,
	    "industry": 24,
	    "industrystring" : "法律服務",
	    "jobcat": 4,
	    "jobcatstring" :"醫事人員",
	    "club_id": 16,
	    "name": "Hehe",
	    "company": "CIRCUM",
	    "phone": "+1 (905) 561-3904",
	    "jobtitle": "Engineer",
	    "otherData": "Hello, function (){return e.surname=c.getItem(\"surnames\"),e.surname}"
	  }
	];